### ISSUE TITLE
Not copying URL

### ISSUE THREAD

**Issue by megaroeny** [kejadlen/giphy.alfredworkflow#4]
It does everything else, but copy the URL for me.

Screen recording here: http://jmp.sh/wI2rTsn

**Comment by kejadlen** [comment]
That is strange... can you take a screenshot of the workflow in Alfred?

**Comment by megaroeny** [comment]
Here ya go:
![image](https://cloud.githubusercontent.com/assets/1559447/19689981/250d2196-9a9d-11e6-8358-7e54179bffd8.png)

**Comment by kejadlen** [comment]
I just released 2.0.1 - can you give that a shot?

https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v2.0.1

**Comment by invious** [comment]
Yeah it's not copying the URL for me either now. Had to change `{var:url}` to `{var:giphy_url}`

**Comment by megaroeny** [comment]
@kejadlen sorry didn't see your comment... I'll give it a try today and follow up.

**Comment by megaroeny** [comment]
So I tried 2.0.2 and it still doesn't copy for some reason 😞  sorry. Maybe I should uninstall and install a fresh one?

**Comment by kejadlen** [comment]
Thanks for finding the fix, @invious!

2.0.3 should fix this issue: https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v2.0.3
